"""empty message

Revision ID: 09eafd24d6d3
Revises: e7e5ff0c69d1
Create Date: 2025-06-09 13:04:02.985218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09eafd24d6d3'
down_revision = 'e7e5ff0c69d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('watches_continue_watching_id_fkey'), type_='foreignkey')
        batch_op.drop_column('continue_watching_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continue_watching_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('watches_continue_watching_id_fkey'), 'shows', ['continue_watching_id'], ['id'])

    # ### end Alembic commands ###
