"""empty message

Revision ID: 1cda054d4efd
Revises: 5448f18b8ee4
Create Date: 2025-05-17 00:06:07.355841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cda054d4efd'
down_revision = '5448f18b8ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_constraint('watches_continue_watching_id_fkey', type_='foreignkey')
        batch_op.drop_column('continue_watching_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continue_watching_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('watches_continue_watching_id_fkey', 'shows', ['continue_watching_id'], ['id'])

    # ### end Alembic commands ###
