"""empty message

Revision ID: 2c3e5524f165
Revises: 
Create Date: 2025-05-16 13:47:22.274667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3e5524f165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('comment', sa.String(length=520), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('review', sa.String(length=520), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=520), nullable=False),
    sa.Column('season', sa.String(length=520), nullable=False),
    sa.Column('episode', sa.String(length=520), nullable=False),
    sa.Column('discription', sa.String(length=520), nullable=False),
    sa.Column('rating', sa.String(length=520), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('review_tag', sa.String(length=520), nullable=False),
    sa.Column('comment_tag', sa.String(length=520), nullable=False),
    sa.Column('show_tag', sa.String(length=520), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('user_bio', sa.String(length=520), nullable=True),
    sa.Column('user_image', sa.String(length=520), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('watch_later_id', sa.Integer(), nullable=False),
    sa.Column('continue_watching_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continue_watching_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ),
    sa.ForeignKeyConstraint(['watch_later_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watches')
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('tags')
    op.drop_table('shows')
    op.drop_table('reviews')
    op.drop_table('comments')
    # ### end Alembic commands ###
