"""empty message

Revision ID: 2f3c6e249ada
Revises: 936f509a3a25
Create Date: 2025-06-10 11:27:42.657061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3c6e249ada'
down_revision = '936f509a3a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_user_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('comments_user_name_key'), ['user_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
