"""empty message

Revision ID: 76266ec1f032
Revises: acb5c42e14da
Create Date: 2025-06-11 14:10:30.837001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76266ec1f032'
down_revision = 'acb5c42e14da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'movies', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
