"""empty message

Revision ID: acb5c42e14da
Revises: 2f3c6e249ada
Create Date: 2025-06-11 14:08:40.665441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb5c42e14da'
down_revision = '2f3c6e249ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=520), nullable=False),
    sa.Column('discription', sa.String(length=520), nullable=False),
    sa.Column('rating', sa.String(length=520), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_movie_later_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'movies', ['watch_movie_later_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('watch_movie_later_id')

    op.drop_table('movies')
    # ### end Alembic commands ###
