"""empty message

Revision ID: b94a1cbd2789
Revises: 74a93166f872
Create Date: 2025-06-10 10:32:45.300422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94a1cbd2789'
down_revision = '74a93166f872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=520), autoincrement=False, nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('text')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###
