"""empty message

Revision ID: ead7e245442a
Revises: 7a71b3c61c36
Create Date: 2025-06-13 14:11:53.190272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead7e245442a'
down_revision = '7a71b3c61c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
        batch_op.alter_column('discription',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)

    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
        batch_op.alter_column('season',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
        batch_op.alter_column('episode',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
        batch_op.alter_column('discription',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
        batch_op.alter_column('discription',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
        batch_op.alter_column('episode',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
        batch_op.alter_column('season',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
        batch_op.alter_column('discription',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)

    # ### end Alembic commands ###
